# Generated by Django 5.1.5 on 2026-01-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.AddField(
            model_name='todolist',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
