# Generated by Django 5.1.5 on 2026-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_portal', '0002_alter_faq_options_remove_announcement_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Document Categories'},
        ),
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
