# Generated by Django 5.1.5 on 2026-04-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_portal', '0003_repair_missing_internal_portal_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaldocumentcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
