# Generated by Django 5.1.5 on 2026-04-10 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_portal', '0012_rms_report_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RmsReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('frequency', models.CharField(db_index=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('submission_deadline_days', models.PositiveSmallIntegerField(default=0)),
                ('before_reminder_days', models.PositiveSmallIntegerField(default=7)),
                ('after_reminder_days', models.PositiveSmallIntegerField(default=0)),
                ('requires_attachment', models.BooleanField(default=True)),
                ('template_file', models.URLField(blank=True, max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rms_report_types_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rms_report_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rms_report_types',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_rms_report_type_code_active')],
            },
        ),
    ]
