# Generated by Django 5.1.5 on 2026-04-11 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0005_group_profile_missing_columns'),
        ('ppaa_portal', '0013_rms_report_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RmsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('financial_year_uid', models.UUIDField(db_index=True)),
                ('financial_period_uid', models.CharField(blank=True, max_length=255)),
                ('financial_period_uids', models.JSONField(blank=True, default=list)),
                ('scope', models.CharField(default='internal', max_length=16)),
                ('priority', models.CharField(default='medium', max_length=16)),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('other_stakeholder_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rms_reports/%Y/%m/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ppaa_portal.rmsreportcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rms_reports_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rms_reports', to='ppaa_auth.department')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='ppaa_portal.rmsreporttype')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ppaa_portal.rmsstakeholder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rms_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rms_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
