# Generated by Django 5.1.5 on 2026-04-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_portal', '0015_rms_report_progress_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsreportprogressentry',
            name='period_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RmsReportPeriodState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_uid', models.CharField(db_index=True, max_length=255)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rms_reports/periods/%Y/%m/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_states', to='ppaa_portal.rmsreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rms_report_period_states',
                'ordering': ['period_uid'],
                'constraints': [models.UniqueConstraint(fields=('report', 'period_uid'), name='unique_rms_report_period_uid')],
            },
        ),
    ]
