# Generated by Django 5.1.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppaa_portal", "0016_rms_report_period_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmsreport",
            name="reminder_before_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the pre-deadline reminder email was sent (at most once).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rmsreport",
            name="reminder_after_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the post-deadline reminder email was sent (at most once).",
                null=True,
            ),
        ),
    ]
