# Generated by Django 5.1.5 on 2026-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_portal', '0020_portalprflyer_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalprflyer',
            name='video_url',
            field=models.CharField(blank=True, default='', help_text='Optional public YouTube or Instagram post/reel URL (used instead of or with a poster image).', max_length=2048),
        ),
    ]
