# Generated by Django 5.1.5 on 2025-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
