# Generated by Django 5.1.5 on 2025-09-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0002_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
