# Generated by Django 5.1.5 on 2025-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0002_alter_user_account_type_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('LONG_TERM', 'Long Term'), ('TEMPORALLY', 'Temporally'), ('SUPER_USER', 'Super User')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('ACTIVE', 'Active'), ('NEW', 'New'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
