# Generated by Django 5.1.5 on 2025-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0004_alter_groupprofile_group_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='check_number',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
