# Generated by Django 5.1.5 on 2025-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0004_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('NEW', 'New'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
