# Generated by Django 5.1.5 on 2025-08-08 02:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0005_alter_user_account_type_alter_user_check_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_location',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='check_number',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pf_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NEW', 'New'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
