# Generated by Django 5.1.5 on 2025-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0005_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
