# Generated by Django 5.1.5 on 2025-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0006_user_office_location_alter_user_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='check_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
