# Generated by Django 5.1.5 on 2025-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0008_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('TEMPORALLY', 'Temporally'), ('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
