# Generated by Django 5.1.5 on 2025-11-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0010_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('TEMPORALLY', 'Temporally'), ('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
