# Generated by Django 5.1.5 on 2025-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0010_userprofile_end_date_alter_user_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
