# Generated by Django 5.1.5 on 2025-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0013_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term'), ('TEMPORALLY', 'Temporally')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
