# Generated by Django 5.1.5 on 2025-11-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0020_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('NEW', 'New'), ('RETIRED', 'Retired'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
