# Generated by Django 5.1.5 on 2025-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0021_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('ACTIVE', 'Active'), ('NEW', 'New'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
