# Generated by Django 5.1.5 on 2025-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0023_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
