# Generated by Django 5.1.5 on 2025-07-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0023_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term'), ('TEMPORALLY', 'Temporally')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
