# Generated by Django 5.1.5 on 2025-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0024_userprofile_acting_user_alter_user_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User')], default='LONG_TERM', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
