# Generated by Django 5.1.5 on 2025-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0024_alter_directory_is_active_alter_user_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
