# Generated by Django 5.1.5 on 2025-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0025_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
