# Generated by Django 5.1.5 on 2025-11-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0025_alter_user_account_type_alter_user_status'),
        ('mnh_auth', '0026_alter_user_account_type_alter_user_status'),
    ]

    operations = [
    ]
