# Generated by Django 5.1.5 on 2025-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0030_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally'), ('LONG_TERM', 'Long Term')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
