# Generated by Django 5.1.5 on 2025-12-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0031_alter_user_status'),
        ('mnh_auth', '0034_alter_user_account_type_alter_user_status'),
    ]

    operations = [
    ]
