# Generated by Django 5.1.5 on 2025-12-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0035_merge_20251205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('NEW', 'New'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
