# Generated by Django 5.1.5 on 2025-12-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0036_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term'), ('TEMPORALLY', 'Temporally')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
