# Generated by Django 5.1.5 on 2026-03-11 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('period_type', models.CharField(choices=[('quarter', 'Quarter'), ('month', 'Month'), ('biannual', 'Bi-Annual')], default='quarter', max_length=20)),
                ('period_number', models.PositiveIntegerField(help_text='Period number (e.g., 1 for Q1, 1-12 for months)')),
                ('name', models.CharField(help_text='e.g., Q1 2025/2026, January 2025', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='ppaa_reports.financialyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Period',
                'verbose_name_plural': 'Financial Periods',
                'db_table': 'ppaa_reports_financial_period',
                'ordering': ['financial_year', 'period_type', 'period_number'],
                'unique_together': {('financial_year', 'period_type', 'period_number')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='financial_period',
            field=models.ForeignKey(blank=True, help_text='Quarter/Period for quarterly/monthly reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ppaa_reports.financialperiod'),
        ),
    ]
