# Generated by Django 5.1.5 on 2026-03-12 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0001_initial'),
        ('ppaa_reports', '0002_add_financial_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='ppaa_reports_directo_422673_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='assigned_to_uid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='directorate_uid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='unit_uid',
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to work on this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Unit/Department within the directorate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='ppaa_auth.department'),
        ),
        migrations.AddField(
            model_name='report',
            name='directory',
            field=models.ForeignKey(blank=True, help_text='Directorate this report belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directory_reports', to='ppaa_auth.department'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['directory', 'financial_year'], name='ppaa_reports_directo_7ddfaf_idx'),
        ),
    ]
