# Generated by Django 5.1.5 on 2026-05-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_reports', '0008_expand_audit_trail_entities'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='ppaa_report_status_b7c4e6_idx',
            old_name='ppaa_reports_status_cb0815_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='ppaa_report_directo_45a121_idx',
            old_name='ppaa_reports_directo_7ddfaf_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='ppaa_report_stakeho_f9e78b_idx',
            old_name='ppaa_reports_stakeho_f8f8d5_idx',
        ),
        migrations.AlterField(
            model_name='reportaudittrail',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('submitted', 'Submitted'), ('downloaded', 'Downloaded'), ('progress_updated', 'Progress Updated'), ('comment_added', 'Comment Added'), ('attachment_uploaded', 'Attachment Uploaded'), ('reminder_sent', 'Reminder Sent'), ('reassigned', 'Reassigned'), ('deleted', 'Deleted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reportsetting',
            name='organization_name',
            field=models.CharField(default='PPAA', help_text='Organization name for reports and notifications', max_length=255),
        ),
    ]
