# Initial migration for ppaa_performance (SPISM). User refs as IntegerField only; no FK to auth_user.

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("deleted_by_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("financial_year", models.CharField(max_length=9)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("approval_comment", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "performance_objectives",
                "ordering": ["financial_year", "title"],
                "verbose_name": "Objective",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("deleted_by_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("planned_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("kpi_name", models.CharField(blank=True, max_length=255)),
                ("kpi_description", models.TextField(blank=True, null=True)),
                ("kpi_unit", models.CharField(blank=True, max_length=100)),
                ("kpi_planned_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("kpi_baseline", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("kpi_direction", models.CharField(default="INCREASE", max_length=20)),
                ("kpi_reporting_frequency", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("approval_comment", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_id", models.IntegerField(blank=True, null=True)),
                ("objective", models.ForeignKey(on_delete=models.CASCADE, related_name="targets", to="ppaa_performance.objective")),
            ],
            options={
                "db_table": "performance_targets",
                "ordering": ["objective", "title"],
                "verbose_name": "Target",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("deleted_by_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("planned_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("approval_comment", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_id", models.IntegerField(blank=True, null=True)),
                ("target", models.ForeignKey(on_delete=models.CASCADE, related_name="activities", to="ppaa_performance.target")),
            ],
            options={
                "db_table": "performance_activities",
                "ordering": ["target", "title"],
                "verbose_name": "Activity",
            },
        ),
        migrations.CreateModel(
            name="QuarterlyData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("deleted_by_id", models.IntegerField(blank=True, null=True)),
                ("quarter", models.PositiveSmallIntegerField(choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")])),
                ("financial_year", models.CharField(max_length=9)),
                ("actual_value", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("computed_ai_percent", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("activity", models.ForeignKey(on_delete=models.CASCADE, related_name="quarterly_data", to="ppaa_performance.activity")),
            ],
            options={
                "db_table": "performance_quarterly_data",
                "ordering": ["activity", "financial_year", "quarter"],
                "unique_together": {("activity", "financial_year", "quarter")},
                "verbose_name": "Quarterly Data",
            },
        ),
        migrations.CreateModel(
            name="KPIActual",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("deleted_by_id", models.IntegerField(blank=True, null=True)),
                ("reporting_period", models.CharField(max_length=50)),
                ("financial_year", models.CharField(max_length=9)),
                ("quarter", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("actual_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("computed_kpi_percent", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("target", models.ForeignKey(on_delete=models.CASCADE, related_name="kpi_actuals", to="ppaa_performance.target")),
            ],
            options={
                "db_table": "performance_kpi_actuals",
                "ordering": ["target", "financial_year", "quarter"],
                "verbose_name": "KPI Actual",
            },
        ),
        migrations.CreateModel(
            name="ActivityDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("deleted_by_id", models.IntegerField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("file_path", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("activity", models.ForeignKey(on_delete=models.CASCADE, related_name="documents", to="ppaa_performance.activity")),
            ],
            options={
                "db_table": "performance_activity_documents",
                "ordering": ["-created_at"],
                "verbose_name": "Activity Document",
            },
        ),
        migrations.CreateModel(
            name="PerformanceAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "performance_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
