# Generated by Django 5.1.5 on 2026-03-02 19:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_performance', '0004_activity_implementation_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='planned_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight % (sum per target = 100)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='activitydocument',
            name='file_path',
            field=models.CharField(help_text='Storage path (e.g. MinIO key)', max_length=500),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='name',
            field=models.CharField(help_text='Format: YYYY/YYYY e.g. 2025/2026', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='kpiactual',
            name='actual_value',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='kpiactual',
            name='reporting_period',
            field=models.CharField(help_text='e.g. Q1 2024/2025', max_length=50),
        ),
        migrations.AlterField(
            model_name='objective',
            name='financial_year',
            field=models.CharField(help_text='e.g. 2024/2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='objective',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight % (sum of all objectives = 100)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='quarterlydata',
            name='actual_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='target',
            name='kpi_baseline',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='target',
            name='kpi_direction',
            field=models.CharField(choices=[('INCREASE', 'Increase favorable'), ('DECREASE', 'Decrease favorable')], default='INCREASE', max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='kpi_planned_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='target',
            name='planned_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight % (sum per objective = 100)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
