# Generated by Cursor on 2026-03-25
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppaa_performance", "0009_target_assignment_fields"),
    ]

    operations = [
        # The columns already exist in the performance_dashboard database.
        # This migration only updates Django's recorded state so the ORM
        # and serializers match the actual schema.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="target",
                    name="kpi_source_type",
                    field=models.CharField(
                        choices=[("DERIVED", "Activity-Driven KPI"), ("DIRECT", "Direct KPI")],
                        default="DERIVED",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="target",
                    name="kpi_calculation_method",
                    field=models.CharField(
                        choices=[("CUMULATIVE", "Cumulative"), ("AVERAGE", "Average")],
                        default="CUMULATIVE",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]

