# Generated by Cursor on 2026-03-25
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppaa_performance", "0010_target_kpi_configuration"),
    ]

    operations = [
        # Columns already exist in the performance_dashboard database.
        # This migration updates Django's recorded model state only.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="quarterlydata",
                    name="implementation_status",
                    field=models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="quarterlydata",
                    name="implementation_submitted_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="quarterlydata",
                    name="implementation_submitted_by_id",
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="quarterlydata",
                    name="implementation_approved_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="quarterlydata",
                    name="implementation_approved_by_id",
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="quarterlydata",
                    name="implementation_approval_comment",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]

