# Generated by Django 5.1.5 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodule',
            name='directory_uid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
