# Generated by Django 5.1.5 on 2025-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodule',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='type',
            field=models.CharField(choices=[('JEEVA_ACCESS', 'JEEVA Access'), ('INTERNET_EMAIL_ACCESS', 'Internet Email Access'), ('EDMS_ACCESS', 'EDMS Access')], default='N/A', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='approvalmodule',
            unique_together={('name', 'code')},
        ),
    ]
