# Generated by Django 5.1.5 on 2025-09-26 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0002_approvalmodule_directory_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmodule',
            name='directory_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
