# Generated by Django 5.1.5 on 2025-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0003_alter_approvalmodule_directory_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='handler_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='is_handled',
            field=models.BooleanField(default=False),
        ),
    ]
