# Generated by Django 5.1.5 on 2025-06-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0003_daterange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daterange',
            old_name='oder',
            new_name='order',
        ),
    ]
