# Generated by Django 5.1.5 on 2025-11-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0004_approvalrequest_handler_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approvalrequesthandler',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestinternetemailaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestjeevaaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
