# Generated by Django 5.1.5 on 2025-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0004_remove_department_unique_department_name_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallevel',
            name='level_order',
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='approvalmodulelevel',
            name='is_signatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='approvalaction',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalaction',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
