# Generated by Django 5.1.5 on 2025-06-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0004_rename_oder_daterange_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daterange',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='date_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='date_range', to='mnh_model.daterange'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
