# Generated by Django 5.1.5 on 2025-04-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0006_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalmodulelevel',
            old_name='action_required',
            new_name='action',
        ),
        migrations.AlterUniqueTogether(
            name='approvalmodulelevel',
            unique_together={('module', 'level', 'action')},
        ),
    ]
