# Generated by Django 5.1.5 on 2025-07-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0006_delete_jeeva_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeevapermission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='mnh_model.jeevarole'),
        ),
        migrations.AddField(
            model_name='jeevarole',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
