# Generated by Django 5.1.5 on 2025-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0007_jeevapermission_role_jeevarole_is_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_state',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvalrequeststep',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
