# Generated by Django 5.1.5 on 2025-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0008_alter_approvalrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequeststep',
            name='action_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalrequeststep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
