# Generated by Django 5.1.5 on 2025-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0008_rename_requestjeeveraccess_requestjeevaaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeevapermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jeevarole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
