# Generated by Django 5.1.5 on 2025-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0009_approvalrequeststep_action_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
