# Generated by Django 5.1.5 on 2025-05-06 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0009_jeevapermission_is_active_jeevarole_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
                'db_table': 'directories',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='directory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='mnh_model.directory'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['name', 'code'], name='directories_name_415e74_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['uid'], name='directories_uid_f7e248_idx'),
        ),
    ]
