# Generated by Django 5.1.5 on 2025-05-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0010_directory_department_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodulelevel',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mnh_model.department'),
        ),
    ]
