# Generated by Django 5.1.5 on 2025-07-09 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0011_approvalrequesthandler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequesthandler',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='approvalrequesthandler',
            name='responded_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler_responded_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
