# Generated by Django 5.1.5 on 2025-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0011_approvalmodulelevel_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestjeevaaccess',
            name='approvalrequest_ptr',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='RequestInternetEmailAccess',
        ),
        migrations.DeleteModel(
            name='RequestJeevaAccess',
        ),
    ]
