# Generated by Django 5.1.5 on 2025-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0013_requestinternetemailaccess_requestjeevaaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='type',
            field=models.CharField(choices=[('JEEVA_ACCESS', 'JEEVA Access Request'), ('INTERNET_EMAIL_ACCESS', 'Internet Email Access Request'), ('EDMS_ACCESS', 'EDMS Access Request')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=15),
        ),
    ]
