# Generated by Django 5.1.5 on 2025-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0014_approvalrequest_type_alter_approvalrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='requested_by',
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='NEW', max_length=15),
        ),
    ]
