# Generated by Django 5.1.5 on 2025-05-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0015_remove_approvalrequest_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mnh_model.department'),
        ),
    ]
