# Generated by Django 5.1.5 on 2025-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0016_approvalrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
