# Generated by Django 5.1.5 on 2025-05-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0017_alter_approvalrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinternetemailaccess',
            name='approval_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internet_email_access', to='mnh_model.approvalrequest'),
        ),
    ]
