# Generated by Django 5.1.5 on 2025-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('predictive', 'Predictive'), ('calibration', 'Calibration'), ('inspection', 'Inspection'), ('upgrade', 'Upgrade'), ('repair', 'Repair'), ('cleaning', 'Cleaning')], default='corrective', max_length=30),
        ),
    ]
