# Generated by Django 5.1.5 on 2025-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_assets', '0002_alter_maintenancerecord_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='storage_type',
            field=models.CharField(choices=[('hdd', 'HDD'), ('SSD', 'SSD'), ('nvme', 'NVMe'), ('hybrid', 'Hybrid (SSHD)'), ('external', 'External'), ('nas', 'Network Attached Storage')], default='ssd', max_length=20),
        ),
    ]
