# Generated by Django 5.1.5 on 2025-11-18 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_assets', '0002_alter_maintenancerecord_maintenance_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-created_at'], 'verbose_name': 'Software Asset', 'verbose_name_plural': 'Software Assets'},
        ),
        migrations.AlterModelOptions(
            name='softwareinstallation',
            options={'ordering': ['-installation_date'], 'verbose_name': 'Software Installation', 'verbose_name_plural': 'Software Installations'},
        ),
        migrations.RemoveField(
            model_name='software',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='software',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='software',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='softwareinstallation',
            unique_together={('software', 'asset')},
        ),
        migrations.AddField(
            model_name='software',
            name='asset_tag',
            field=models.CharField(default='AUTO', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='software',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_assets.assettype'),
        ),
        migrations.AddField(
            model_name='software',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='software',
            name='documentation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='installation_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='license_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_assets.location'),
        ),
        migrations.AddField(
            model_name='software',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='software_assets/'),
        ),
        migrations.AddField(
            model_name='software',
            name='platform',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS'), ('web', 'Web-based'), ('cross_platform', 'Cross-platform'), ('android', 'Android'), ('ios', 'iOS')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='software',
            name='software_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='software',
            name='software_type',
            field=models.CharField(blank=True, choices=[('application', 'Application'), ('operating_system', 'Operating System'), ('utility', 'Utility'), ('development_tool', 'Development Tool'), ('database', 'Database'), ('security', 'Security'), ('productivity', 'Productivity'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('operational', 'Operational'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='software',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_assets.supplier'),
        ),
        migrations.AddField(
            model_name='software',
            name='support_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='system_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='total_licenses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='software',
            name='used_licenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='software',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_software', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='compliance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='configuration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='installation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='installation_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='is_compliant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='last_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='license_key_used',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Installation'), ('failed', 'Installation Failed'), ('uninstalled', 'Uninstalled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='uninstall_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='uninstall_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='uninstalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uninstalled_software', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='version_installed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('load_balancer', 'Load Balancer'), ('gateway', 'Gateway'), ('modem', 'Modem'), ('hub', 'Hub'), ('bridge', 'Bridge'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='connection_type',
            field=models.CharField(choices=[('usb', 'USB'), ('bluetooth', 'Bluetooth'), ('wireless', 'Wireless'), ('hdmi', 'HDMI'), ('vga', 'VGA'), ('ps2', 'PS/2'), ('ethernet', 'Ethernet'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='peripheral_type',
            field=models.CharField(choices=[('printer', 'Printer'), ('scanner', 'Scanner'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('speaker', 'Speaker'), ('webcam', 'Webcam'), ('headset', 'Headset'), ('microphone', 'Microphone'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ict_assets.softwarecategory'),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('open_source', 'Open Source'), ('trial', 'Trial'), ('enterprise', 'Enterprise'), ('volume', 'Volume License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_installations', to='ict_assets.asset'),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='ict_assets.software'),
        ),
        migrations.AlterModelTable(
            name='software',
            table='software_assets',
        ),
        migrations.AlterModelTable(
            name='softwareinstallation',
            table='software_installations',
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='available', max_length=20)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='ict_assets.software')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software License',
                'verbose_name_plural': 'Software Licenses',
                'db_table': 'software_licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='license_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_assets.softwarelicense'),
        ),
        migrations.RemoveField(
            model_name='softwareinstallation',
            name='installed_date',
        ),
        migrations.RemoveField(
            model_name='softwareinstallation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='softwareinstallation',
            name='license_key',
        ),
    ]
