# Generated by Django 5.1.5 on 2025-11-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_assets', '0003_alter_software_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='photo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
