services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: ppaa_portal_db
    ports:
      - "5433:5432"
    volumes:
      - /opt/ppaa-data/postgres:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - ppaa-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ppaa.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - "8099:80"
    volumes:
      - /opt/ppaa-data/pgadmin:/var/lib/pgadmin
    networks:
      - ppaa-network
    depends_on:
      - postgres
  # mysql:
    # image: mysql:8.0
    # container_name: mysql
    # restart: always
    # environment:
    #   MYSQL_DATABASE: analytics_db
    #   MYSQL_USER: analytics
    #   MYSQL_PASSWORD: analytics@MNH25
    #   MYSQL_ROOT_PASSWORD: P@ssw0rd
    # ports:
    #   - "3307:3306"
    # volumes:
    #   - /opt/mnh-data/mysql-analytics:/var/lib/mysql
    # networks:
    #   - mnh-network
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ppaa-network

  backend:
    image: ppaa-internal-portal-backend
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ppaa-network
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      # PostgreSQL
      POSTGRES_DB_NAME: "ppaa_portal_db"
      POSTGRES_DB_USER: "postgres"
      POSTGRES_DB_PWD: "P@ssw0rd"
      POSTGRES_DB_HOST: "postgres"
      POSTGRES_DB_PORT: 5432


# Maoni Microservice Database
      MAONI_DB_NAME: "maoni_db"
      MAONI_DB_USER: "postgres"
      MAONI_DB_PWD: "P@ssw0rd"
      MAONI_DB_HOST: "postgres"
      MAONI_DB_PORT: 5432

      # PPAA Reports Database
      REPORTS_DB_NAME: "ppaa_reports"
      RMS_REPORTS_BUCKET: "reports-management"


      # 🔥 EMAIL SETTINGS (LIVE GMAIL)
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ppaa@gmail.com
      EMAIL_HOST_PASSWORD: "fzlf psfi zpmf uiyw"
      EMAIL_USE_TLS: "True"
      DEFAULT_FROM_EMAIL: ppaa@gmail.com

      # 🔥 CELERY + REDIS
      CELERY_BROKER_URL: redis://redis:6379/0
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

  celery_worker:
    image: ppaa-internal-portal-backend
    container_name: celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A ppaa_portal.config.celery_app worker --loglevel=info

    volumes:
      - ./:/app
    networks:
      - ppaa-network
    environment:
      # Same DB connection
      POSTGRES_DB_NAME: "ppaa_portal_db"
      POSTGRES_DB_USER: "postgres"
      POSTGRES_DB_PWD: "P@ssw0rd"
      POSTGRES_DB_HOST: "postgres"
      POSTGRES_DB_PORT: 5432

      # PPAA Reports Database
      REPORTS_DB_NAME: "ppaa_reports"
      RMS_REPORTS_BUCKET: "reports-management"

  

      # Same EMAIL SETTINGS
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ppaa@gmail.com
      EMAIL_HOST_PASSWORD: "fzlf psfi zpmf uiyw"
      EMAIL_USE_TLS: "True"
      DEFAULT_FROM_EMAIL: ppaa@gmail.com

      # Celery + Redis
      CELERY_BROKER_URL: redis://redis:6379/0
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8092:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - ppaa-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rachel.sironga
      MINIO_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - /opt/ppaa-data/minio-data:/data
    networks:
      - ppaa-network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  ppaa-network:
    driver: bridge
    external: true
