# Generated by Django 5.1.5 on 2025-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_training', '0003_departmentallocation_trainingbatch_uid_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='departments',
        ),
        migrations.AddField(
            model_name='application',
            name='department_uids',
            field=models.JSONField(blank=True, default=list, help_text='List of department UIDs from auth microservice'),
        ),
    ]
