# Generated by Django 5.1.5 on 2025-12-21 09:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_training', '0004_remove_application_departments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('student_id_format', models.CharField(default='STD-{YYYY}-{NNNN}', help_text='Format pattern for student ID (e.g., STD-{YYYY}-{NNNN}, {YYYY} = year, {NNNN} = sequential)', max_length=100)),
                ('student_id_prefix', models.CharField(default='STD', help_text='Prefix for student ID', max_length=10)),
                ('student_id_increment_counter', models.PositiveIntegerField(default=1, help_text='Current counter for student ID generation', validators=[django.core.validators.MinValueValidator(1)])),
                ('reset_student_counter_yearly', models.BooleanField(default=True, help_text='Reset student ID counter at the beginning of each year')),
                ('application_ref_format', models.CharField(default='APP-{YYYY}-{NNNN}', help_text='Format pattern for application reference (e.g., APP-{YYYY}-{NNNN})', max_length=100)),
                ('application_ref_prefix', models.CharField(default='APP', help_text='Prefix for application reference number', max_length=10)),
                ('application_ref_counter', models.PositiveIntegerField(default=1, help_text='Current counter for application reference generation', validators=[django.core.validators.MinValueValidator(1)])),
                ('reset_application_counter_yearly', models.BooleanField(default=True, help_text='Reset application counter at the beginning of each year')),
                ('certificate_number_format', models.CharField(default='CERT-{YYYY}-{NNNN}', help_text='Format pattern for certificate number (e.g., CERT-{YYYY}-{NNNN})', max_length=100)),
                ('certificate_number_prefix', models.CharField(default='CERT', help_text='Prefix for certificate number', max_length=10)),
                ('certificate_counter', models.PositiveIntegerField(default=1, help_text='Current counter for certificate generation', validators=[django.core.validators.MinValueValidator(1)])),
                ('reset_certificate_counter_yearly', models.BooleanField(default=True, help_text='Reset certificate counter at the beginning of each year')),
                ('training_hours_per_week', models.PositiveIntegerField(default=40, help_text='Standard training hours per week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('training_days_per_week', models.PositiveIntegerField(default=5, help_text='Standard number of training days per week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('standard_training_duration', models.PositiveIntegerField(default=12, help_text='Standard training duration (value)', validators=[django.core.validators.MinValueValidator(1)])),
                ('standard_training_duration_unit', models.CharField(choices=[('W', 'Weeks'), ('M', 'Months'), ('D', 'Days')], default='W', help_text='Unit for standard training duration', max_length=1)),
                ('special_departments', models.JSONField(blank=True, default=dict, help_text='Special department configurations with custom training hours/duration (format: {dept_uid: {hours_per_week: int, duration_value: int, duration_unit: str, special_requirements: str}})')),
                ('min_training_days', models.PositiveIntegerField(default=1, help_text='Minimum number of days per department allocation', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_training_days', models.PositiveIntegerField(default=365, help_text='Maximum number of days per department allocation', validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_overlapping_departments', models.BooleanField(default=False, help_text='Allow training in multiple departments simultaneously')),
                ('organization_name', models.CharField(default='MNH Training Center', help_text='Organization name for certificates and official documents', max_length=255)),
                ('certificate_validity_years', models.PositiveIntegerField(default=0, help_text='Certificate validity period in years (0 = indefinite)')),
                ('minimum_attendance_percentage', models.PositiveIntegerField(default=80, help_text='Minimum attendance percentage required to receive certificate', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('require_supervisor_approval', models.BooleanField(default=True, help_text='Require supervisor approval before training completion')),
                ('days_before_training_reminder', models.PositiveIntegerField(default=7, help_text='Send reminder notification N days before training starts')),
                ('notify_on_completion', models.BooleanField(default=True, help_text='Send notification when training is completed')),
                ('last_modified_by_guid', models.CharField(blank=True, help_text='GUID of user who last modified these settings', max_length=36, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Setting',
                'verbose_name_plural': 'Training Settings',
            },
        ),
    ]
