# Generated by Django 5.1.5 on 2025-12-21 09:46

import django.core.validators
import django.db.models.deletion
import functools
import microservices.mnh_training.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_training', '0005_add_training_settings_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor_uid', models.CharField(help_text='UID reference to Supervisor', max_length=36)),
                ('session_number', models.PositiveIntegerField(help_text='Session sequence number within batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expected_attendees', models.PositiveIntegerField(default=0, help_text='Expected number of attendees', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('ON', 'Ongoing'), ('CP', 'Completed'), ('CN', 'Cancelled')], db_index=True, default='SC', max_length=2)),
                ('materials_provided', models.FileField(blank=True, help_text='Training materials/handouts', null=True, upload_to=functools.partial(microservices.mnh_training.models.year_based_upload_path, *(), **{'prefix': 'training_materials'}))),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='mnh_training.trainingbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('department_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='mnh_training.departmentallocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-session_date', 'session_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused Absence')], db_index=True, max_length=1)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_attendance', to='mnh_training.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='mnh_training.trainingsession')),
            ],
            options={
                'verbose_name': 'Training Attendance',
                'verbose_name_plural': 'Training Attendances',
                'ordering': ['session', 'application__student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssessment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_type', models.CharField(choices=[('PRE', 'Pre-Training Assessment'), ('MID', 'Mid-Training Assessment'), ('PST', 'Post-Training Assessment'), ('PRC', 'Practical Assessment'), ('WRT', 'Written Assessment')], db_index=True, max_length=3)),
                ('assessment_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, help_text='Score out of 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.DecimalField(decimal_places=2, default=100, help_text='Total possible score', max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('graded_by_guid', models.CharField(help_text='UID reference to grader', max_length=36)),
                ('feedback', models.TextField(blank=True)),
                ('assessment_file', models.FileField(blank=True, help_text='Assessment document/answer sheet', null=True, upload_to=functools.partial(microservices.mnh_training.models.year_based_upload_path, *(), **{'prefix': 'assessments'}))),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_assessments', to='mnh_training.application')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='mnh_training.trainingbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Assessment',
                'verbose_name_plural': 'Training Assessments',
                'ordering': ['-assessment_date', 'application'],
                'indexes': [models.Index(fields=['batch', 'assessment_type'], name='mnh_trainin_batch_i_82ab6f_idx'), models.Index(fields=['application', 'assessment_type'], name='mnh_trainin_applica_b4fdc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'application', 'assessment_type'), name='unique_batch_application_assessment_type')],
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PD', 'Pending Issue'), ('IS', 'Issued'), ('RV', 'Revoked')], db_index=True, default='DR', max_length=2)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, help_text='Final attendance percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_assessment_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final assessment score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('issued_by_guid', models.CharField(blank=True, help_text='UID reference to issuer', max_length=36, null=True)),
                ('revoked_by_guid', models.CharField(blank=True, help_text='UID reference to revoker', max_length=36, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Certificate PDF document', null=True, upload_to=functools.partial(microservices.mnh_training.models.year_based_upload_path, *(), **{'prefix': 'certificates'}))),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_certificates', to='mnh_training.application')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='mnh_training.trainingbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Certificate',
                'verbose_name_plural': 'Training Certificates',
                'ordering': ['-issue_date', 'application'],
                'indexes': [models.Index(fields=['batch', 'status'], name='mnh_trainin_batch_i_17cfde_idx'), models.Index(fields=['application', 'status'], name='mnh_trainin_applica_fd5772_idx'), models.Index(fields=['certificate_number'], name='mnh_trainin_certifi_abc09f_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'application'), name='unique_batch_application_certificate')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['batch', 'session_date'], name='mnh_trainin_batch_i_2c70cf_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['status', 'session_date'], name='mnh_trainin_status_bf06b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('batch', 'session_number'), name='unique_batch_session_number'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['session', 'status'], name='mnh_trainin_session_889284_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['application', 'session'], name='mnh_trainin_applica_bbd128_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingattendance',
            constraint=models.UniqueConstraint(fields=('session', 'application'), name='unique_session_application_attendance'),
        ),
    ]
