# Generated by Django 5.1.5 on 2026-04-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maoni', '0003_ensure_default_categories'),
    ]

    operations = []
