# Generated by Django 5.1.5 on 2026-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maoni", "0005_alter_maonisettings_eas_sla_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maonisuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_HANDLER_REVIEW", "Under handler review"),
                    ("ESCALATED_TO_REVIEWER", "Escalated to reviewer"),
                    ("RETURNED_TO_HANDLER", "Returned to handler"),
                    ("HANDLER_RESPONDED_TO_REVIEWER", "Handler responded to reviewer"),
                    ("HANDLER_RESPONDED_TO_CONTRIBUTOR", "Handler responded to contributor"),
                    ("CLOSED_APPROVED", "Closed - approved"),
                    ("CLOSED_REJECTED", "Closed - rejected"),
                ],
                default="DRAFT",
                max_length=40,
            ),
        ),
    ]
