# Generated by Django 5.1.5 on 2026-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoni', '0012_workflow_close_outcomes_contributor_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maonisuggestioncomment',
            name='thread_scope',
            field=models.CharField(choices=[('CONTRIBUTOR', 'Contributor-visible thread'), ('STAFF', 'Staff-only (handler & institutional reviewer)')], db_index=True, default='CONTRIBUTOR', max_length=20),
        ),
    ]
