# Generated by Django 5.1.5 on 2026-04-09 02:46

from datetime import date

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_default_financial_year(apps, schema_editor):
    SpismFinancialYear = apps.get_model("ppaa_performance", "SpismFinancialYear")
    if SpismFinancialYear.objects.filter(name="2025/2026").exists():
        return
    SpismFinancialYear.objects.create(
        name="2025/2026",
        start_date=date(2025, 7, 1),
        end_date=date(2026, 6, 30),
        is_active=True,
        is_deleted=False,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpismFinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spism_financial_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RunPython(seed_default_financial_year, migrations.RunPython.noop),
    ]
