# Generated by Django 5.1.5 on 2026-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_performance', '0003_spismactivity_approval_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spismactivity',
            name='approval_comment',
            field=models.TextField(blank=True, help_text='Latest planning (ES) return comment when status is RETURNED.'),
        ),
    ]
