# Generated by Django 5.1.5 on 2026-01-26 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoniCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('GENERAL', 'General'), ('DEPARTMENTAL', 'Departmental'), ('STRATEGIC', 'Strategic'), ('OPERATIONAL', 'Operational')], default='GENERAL', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#4f46e5', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Maoni Categories',
                'db_table': 'maoni_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Maoni',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department_uid', models.CharField(blank=True, help_text='Department UID from ppaa_auth app', max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='SUBMITTED', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by_id', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Area of concern', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maoni', to='ppaa_maoni.maonicategory')),
            ],
            options={
                'verbose_name_plural': 'Maoni',
                'db_table': 'maoni',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaoniComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('commented_by_id', models.IntegerField(blank=True, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('maoni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ppaa_maoni.maoni')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply to another comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ppaa_maoni.maonicomment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maoni_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maoni',
            index=models.Index(fields=['status'], name='maoni_status_a4a45f_idx'),
        ),
        migrations.AddIndex(
            model_name='maoni',
            index=models.Index(fields=['priority'], name='maoni_priorit_c5ab6c_idx'),
        ),
        migrations.AddIndex(
            model_name='maoni',
            index=models.Index(fields=['category'], name='maoni_categor_379b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='maoni',
            index=models.Index(fields=['department_uid'], name='maoni_departm_68bf17_idx'),
        ),
        migrations.AddIndex(
            model_name='maoni',
            index=models.Index(fields=['submitted_at'], name='maoni_submitt_5cb848_idx'),
        ),
    ]
