# Generated by Django 5.1.5 on 2025-12-18 09:24

import microservices.mnh_analytical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text='The name of the department', max_length=250, verbose_name='department name')),
                ('code', models.CharField(help_text='Short code identifier for the department', max_length=50, unique=True, verbose_name='department code')),
                ('description', models.TextField(blank=True, help_text='Additional details about the department', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'analyticsApp_department',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(help_text='The date this attendance was recorded', verbose_name='attendance date')),
                ('attendance_report', models.FileField(blank=True, help_text='Original uploaded attendance file (Excel or CSV)', null=True, upload_to=microservices.mnh_analytical.models.Attendance.clinic_attendance_upload_path, verbose_name='attendance report')),
                ('total_new_patients', models.PositiveIntegerField(default=0, help_text='Total number of new patients', verbose_name='total new patients')),
                ('total_follow_up_patients', models.PositiveIntegerField(default=0, help_text='Total number of follow-up patients', verbose_name='total follow-up patients')),
                ('grand_total_patients', models.PositiveIntegerField(default=0, help_text='Grand total number of patients', verbose_name='grand total patients')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance record', null=True, verbose_name='notes')),
                ('processed_date', models.DateField(blank=True, help_text='The date this attendance was processed', null=True, verbose_name='processed date')),
                ('total_column', models.PositiveIntegerField(default=0, verbose_name='total excel colums')),
                ('success_colums', models.PositiveIntegerField(default=0, verbose_name='total success columns')),
                ('failed_colums', models.PositiveIntegerField(default=0, verbose_name='total failed colum')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'db_table': 'analyticsApp_attendance',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The name of the block/building', max_length=255, verbose_name='block name')),
                ('code', models.CharField(help_text='Short code identifier for the block', max_length=50, verbose_name='block code')),
                ('location', models.CharField(blank=True, choices=[('Upanga', 'Upanga'), ('Mloganzila', 'Mloganzila')], default='Upanga', help_text='Geographical location description of the block', max_length=100, null=True, verbose_name='location')),
                ('description', models.TextField(blank=True, help_text='Additional details about the block', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
                'db_table': 'analyticsApp_block',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The name of the clinic', max_length=250, verbose_name='clinic name')),
                ('code', models.CharField(help_text='Short code identifier for the clinic', max_length=50, verbose_name='clinic code')),
                ('description', models.TextField(blank=True, help_text='Additional details about the clinic', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'clinic',
                'verbose_name_plural': 'clinics',
                'db_table': 'analyticsApp_clinic',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('new_patients', models.PositiveIntegerField(default=0, help_text='Number of new patients', verbose_name='new patients')),
                ('follow_up_patients', models.PositiveIntegerField(default=0, help_text='Number of follow-up patients', verbose_name='follow-up patients')),
                ('total_patients', models.PositiveIntegerField(default=0, help_text='Number of patients', verbose_name='total patients')),
            ],
            options={
                'verbose_name': 'patient attendance',
                'verbose_name_plural': 'Patient attendances',
                'db_table': 'analyticsApp_patientattendance',
                'ordering': ['-attendance__date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the payment method', max_length=250, verbose_name='payment mode')),
                ('code', models.CharField(help_text='Short code identifier for the payment method', max_length=50, unique=True, verbose_name='payment code')),
                ('description', models.TextField(blank=True, help_text='Additional details about the payment method', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'payment mode',
                'verbose_name_plural': 'payment modes',
                'db_table': 'analyticsApp_paymentmode',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
