# Generated by Django 5.1.5 on 2025-12-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_analytical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text='The name of the department', max_length=250, verbose_name='department name')),
                ('code', models.CharField(help_text='Short code identifier for the department', max_length=50, unique=True, verbose_name='department code')),
                ('description', models.TextField(blank=True, help_text='Additional details about the department', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'analyticsApp_department',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': False, 'ordering': ['-date'], 'verbose_name': 'attendance', 'verbose_name_plural': 'attendances'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'block', 'verbose_name_plural': 'blocks'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'clinic', 'verbose_name_plural': 'clinics'},
        ),
        migrations.AlterModelOptions(
            name='patientattendance',
            options={'managed': False, 'ordering': ['-attendance__date'], 'verbose_name': 'patient attendance', 'verbose_name_plural': 'Patient attendances'},
        ),
        migrations.AlterModelOptions(
            name='paymentmode',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'payment mode', 'verbose_name_plural': 'payment modes'},
        ),
    ]
