# Generated by Django 5.1.5 on 2025-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_analytical', '0002_department_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='analyticsApp_attendance',
        ),
        migrations.AlterModelTable(
            name='block',
            table='analyticsApp_block',
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='analyticsApp_clinic',
        ),
        migrations.AlterModelTable(
            name='patientattendance',
            table='analyticsApp_patientattendance',
        ),
        migrations.AlterModelTable(
            name='paymentmode',
            table='analyticsApp_paymentmode',
        ),
    ]
