from django.urls import path

from ppaa_portal.reports_management_views import (
    RmsAuditTrailListView,
    RmsAuditTrailStatsView,
    RmsDashboardCalendarView,
    RmsDashboardDirectorateView,
    RmsDashboardStatsView,
    RmsDepartmentsListView,
    RmsFinancialPeriodsListView,
    RmsFinancialYearCreateView,
    RmsFinancialYearDeleteView,
    RmsFinancialYearDetailView,
    RmsFinancialYearPeriodsView,
    RmsFinancialYearsListView,
    RmsFinancialYearUpdateView,
    RmsReportCategoriesListView,
    RmsReportCategoryCreateView,
    RmsReportCategoryDeleteView,
    RmsReportCategoryDetailView,
    RmsReportCategoryUpdateView,
    RmsReportAttachmentDownloadView,
    RmsReportAttachmentPreviewView,
    RmsReportAuditTrailForReportView,
    RmsReportCreateView,
    RmsReportDeleteView,
    RmsReportDetailView,
    RmsReportsGroupedListView,
    RmsReportProgressView,
    RmsReportSubmitView,
    RmsReportUpdateView,
    RmsReportTypeCreateView,
    RmsReportTypeDeleteView,
    RmsReportTypeDetailView,
    RmsReportTypesListView,
    RmsReportTypeUpdateView,
    RmsStakeholderCreateView,
    RmsStakeholderDeleteView,
    RmsStakeholderDetailView,
    RmsStakeholdersListView,
    RmsStakeholderUpdateView,
    RmsUserProfileForReportsView,
)

urlpatterns = [
    path("user-profile", RmsUserProfileForReportsView.as_view()),
    path("user-profile/", RmsUserProfileForReportsView.as_view()),
    path("financial-years/create", RmsFinancialYearCreateView.as_view()),
    path("financial-years/create/", RmsFinancialYearCreateView.as_view()),
    path(
        "financial-years/<uuid:uid>/update",
        RmsFinancialYearUpdateView.as_view(),
    ),
    path(
        "financial-years/<uuid:uid>/update/",
        RmsFinancialYearUpdateView.as_view(),
    ),
    path(
        "financial-years/<uuid:uid>/delete",
        RmsFinancialYearDeleteView.as_view(),
    ),
    path(
        "financial-years/<uuid:uid>/delete/",
        RmsFinancialYearDeleteView.as_view(),
    ),
    path(
        "financial-years/<uuid:uid>/periods",
        RmsFinancialYearPeriodsView.as_view(),
    ),
    path(
        "financial-years/<uuid:uid>/periods/",
        RmsFinancialYearPeriodsView.as_view(),
    ),
    path("financial-years/<uuid:uid>", RmsFinancialYearDetailView.as_view()),
    path("financial-years/<uuid:uid>/", RmsFinancialYearDetailView.as_view()),
    path("financial-years", RmsFinancialYearsListView.as_view()),
    path("financial-years/", RmsFinancialYearsListView.as_view()),
    path("financial-periods", RmsFinancialPeriodsListView.as_view()),
    path("financial-periods/", RmsFinancialPeriodsListView.as_view()),
    path("report-types/create", RmsReportTypeCreateView.as_view()),
    path("report-types/create/", RmsReportTypeCreateView.as_view()),
    path(
        "report-types/<uuid:uid>/update",
        RmsReportTypeUpdateView.as_view(),
    ),
    path(
        "report-types/<uuid:uid>/update/",
        RmsReportTypeUpdateView.as_view(),
    ),
    path(
        "report-types/<uuid:uid>/delete",
        RmsReportTypeDeleteView.as_view(),
    ),
    path(
        "report-types/<uuid:uid>/delete/",
        RmsReportTypeDeleteView.as_view(),
    ),
    path("report-types/<uuid:uid>", RmsReportTypeDetailView.as_view()),
    path("report-types/<uuid:uid>/", RmsReportTypeDetailView.as_view()),
    path("report-types", RmsReportTypesListView.as_view()),
    path("report-types/", RmsReportTypesListView.as_view()),
    path("report-categories/create", RmsReportCategoryCreateView.as_view()),
    path("report-categories/create/", RmsReportCategoryCreateView.as_view()),
    path(
        "report-categories/<uuid:uid>/update",
        RmsReportCategoryUpdateView.as_view(),
    ),
    path(
        "report-categories/<uuid:uid>/update/",
        RmsReportCategoryUpdateView.as_view(),
    ),
    path(
        "report-categories/<uuid:uid>/delete",
        RmsReportCategoryDeleteView.as_view(),
    ),
    path(
        "report-categories/<uuid:uid>/delete/",
        RmsReportCategoryDeleteView.as_view(),
    ),
    path(
        "report-categories/<uuid:uid>",
        RmsReportCategoryDetailView.as_view(),
    ),
    path(
        "report-categories/<uuid:uid>/",
        RmsReportCategoryDetailView.as_view(),
    ),
    path("report-categories", RmsReportCategoriesListView.as_view()),
    path("report-categories/", RmsReportCategoriesListView.as_view()),
    path("departments", RmsDepartmentsListView.as_view()),
    path("departments/", RmsDepartmentsListView.as_view()),
    path("stakeholders/create", RmsStakeholderCreateView.as_view()),
    path("stakeholders/create/", RmsStakeholderCreateView.as_view()),
    path(
        "stakeholders/<uuid:uid>/update",
        RmsStakeholderUpdateView.as_view(),
    ),
    path(
        "stakeholders/<uuid:uid>/update/",
        RmsStakeholderUpdateView.as_view(),
    ),
    path(
        "stakeholders/<uuid:uid>/delete",
        RmsStakeholderDeleteView.as_view(),
    ),
    path(
        "stakeholders/<uuid:uid>/delete/",
        RmsStakeholderDeleteView.as_view(),
    ),
    path("stakeholders/<uuid:uid>", RmsStakeholderDetailView.as_view()),
    path("stakeholders/<uuid:uid>/", RmsStakeholderDetailView.as_view()),
    path("stakeholders", RmsStakeholdersListView.as_view()),
    path("stakeholders/", RmsStakeholdersListView.as_view()),
    path("reports/create", RmsReportCreateView.as_view()),
    path("reports/create/", RmsReportCreateView.as_view()),
    path("reports/<uuid:uid>/update", RmsReportUpdateView.as_view()),
    path("reports/<uuid:uid>/update/", RmsReportUpdateView.as_view()),
    path("reports/<uuid:uid>/delete", RmsReportDeleteView.as_view()),
    path("reports/<uuid:uid>/delete/", RmsReportDeleteView.as_view()),
    path("reports/<uuid:uid>/progress", RmsReportProgressView.as_view()),
    path("reports/<uuid:uid>/progress/", RmsReportProgressView.as_view()),
    path("reports/<uuid:uid>/submit", RmsReportSubmitView.as_view()),
    path("reports/<uuid:uid>/submit/", RmsReportSubmitView.as_view()),
    path(
        "reports/<uuid:uid>/audit-trail",
        RmsReportAuditTrailForReportView.as_view(),
    ),
    path(
        "reports/<uuid:uid>/audit-trail/",
        RmsReportAuditTrailForReportView.as_view(),
    ),
    path("reports/<uuid:uid>/preview", RmsReportAttachmentPreviewView.as_view()),
    path("reports/<uuid:uid>/preview/", RmsReportAttachmentPreviewView.as_view()),
    path("reports/<uuid:uid>/download", RmsReportAttachmentDownloadView.as_view()),
    path("reports/<uuid:uid>/download/", RmsReportAttachmentDownloadView.as_view()),
    path("reports/<uuid:uid>", RmsReportDetailView.as_view()),
    path("reports/<uuid:uid>/", RmsReportDetailView.as_view()),
    path("reports-grouped", RmsReportsGroupedListView.as_view()),
    path("reports-grouped/", RmsReportsGroupedListView.as_view()),
    path("dashboard", RmsDashboardStatsView.as_view()),
    path("dashboard/", RmsDashboardStatsView.as_view()),
    path(
        "dashboard/directorate/<uuid:uid>",
        RmsDashboardDirectorateView.as_view(),
    ),
    path(
        "dashboard/directorate/<uuid:uid>/",
        RmsDashboardDirectorateView.as_view(),
    ),
    path("dashboard/calendar", RmsDashboardCalendarView.as_view()),
    path("dashboard/calendar/", RmsDashboardCalendarView.as_view()),
    path("audit-trail/stats", RmsAuditTrailStatsView.as_view()),
    path("audit-trail/stats/", RmsAuditTrailStatsView.as_view()),
    path("audit-trail", RmsAuditTrailListView.as_view()),
    path("audit-trail/", RmsAuditTrailListView.as_view()),
]
