"""
Django settings for eapproval_api project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

from .db_router import ROUTERS as DATABASE_ROUTERS

load_dotenv()

from .db_config import build_databases
from .network_defaults import LAN_HOST, lan_browser_origins, merge_unique_origins

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Disable automatic HTTPS redirection
    SESSION_COOKIE_SECURE = True  # Ensure session cookies are not HTTPS-only
    CSRF_COOKIE_SECURE = True # Ensure CSRF cookies are not HTTPS-only
    SECURE_HSTS_SECONDS = 31536000 # Disable HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# MinIO configuration (S3-compatible API via django-storages + boto3)
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
RMS_REPORTS_BUCKET = os.getenv("RMS_REPORTS_BUCKET", "reports-management")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"

AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_FILE_OVERWRITE = False


# Optional (avoid automatic URL signing)
AWS_QUERYSTRING_AUTH = False


ALLOWED_HOSTS = ['*']
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "utils.api_exception_handle.custom_api_exception_handler",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=10),
    # "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    # "REFRESH_TOKEN_LIFETIME": timedelta(minutes=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,


}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
# CORS_ALLOW_ALL_ORIGINS = True
_CORS_BASE_PROD = [
    "http://minio.ppaa",
    "http://localhost:8092",
    "http://127.0.0.1:8092",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    f"http://{LAN_HOST}:8092",
]
CORS_ALLOWED_ORIGINS = merge_unique_origins(_CORS_BASE_PROD, lan_browser_origins())
CSRF_TRUSTED_ORIGINS = merge_unique_origins(_CORS_BASE_PROD, lan_browser_origins())

FRONTEND_URL = (os.environ.get("FRONTEND_URL") or f"http://{LAN_HOST}:3000").strip()




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'ppaa_portal',
    'ppaa_auth',
    # Some routes import from `ppaa_performance.*` (non-microservices package).
    # Keep it installed so Django can register those models.
    'ppaa_performance',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_yasg',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'microservices.maoni',
    # Reports module lives in `microservices.ppaa_reports` in this repo.
    'microservices.ppaa_reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ppaa_portal.audit_middleware.ApiActivityAuditMiddleware',
]



REST_FRAMEWORK.update({
    'DEFAULT_THROTTLE_RATES': {
        'user': '5000/day',      # Allow authenticated users 500 requests per day
        'anon': '10/minute',    # Allow anonymous users 20 requests per minute
        'burst': '5/second',   # Allow short bursts of 5 requests per second
        'sustained': '50/hour', # Limit long-term users to 50 requests per hour
    },
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
})


ROOT_URLCONF = 'ppaa_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ppaa_portal.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'ppaa_auth.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

AUTH_USER_MODEL = 'ppaa_auth.User'
DATABASES = build_databases(
    reports_keys={
        "name_key": "REPORTS_MANAGEMENT_DB_NAME",
        "user_key": "REPORTS_MANAGEMENT_DB_USER",
        "pwd_key": "REPORTS_MANAGEMENT_DB_PWD",
        "host_key": "REPORTS_MANAGEMENT_DB_HOST",
        "port_key": "REPORTS_MANAGEMENT_DB_PORT",
    },
)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS=True
EMAIL_USE_SSL=True
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = os.getenv("EMAIL_PORT")
APPEND_SLASH=False
DEFAULT_FROM_EMAIL=os.getenv("DEFAULT_FROM_EMAIL")
