"""
Django settings for eapproval_api project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

load_dotenv()

from celery.schedules import crontab

from .db_config import build_databases
from .db_router import ROUTERS as DATABASE_ROUTERS
from .network_defaults import LAN_HOST, lan_browser_origins, merge_unique_origins

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Disable automatic HTTPS redirection
    SESSION_COOKIE_SECURE = True  # Ensure session cookies are not HTTPS-only
    CSRF_COOKIE_SECURE = True # Ensure CSRF cookies are not HTTPS-only
    SECURE_HSTS_SECONDS = 31536000 # Disable HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# MinIO configuration (S3-compatible API via django-storages + boto3)
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")  # e.g. http://minio:9000 in Docker
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
SPM_BUCKET_NAME = os.getenv("SPM_BUCKET_NAME", "strategic-performance-management")
RMS_REPORTS_BUCKET = os.getenv("RMS_REPORTS_BUCKET", "reports-management")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"

# MinIO / S3 client behaviour (portal uploads: documents, PR flyers, popup images, etc.)
AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_FILE_OVERWRITE = False

# Optional (avoid automatic URL signing)
AWS_QUERYSTRING_AUTH = False


ALLOWED_HOSTS = ['*']
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "utils.api_exception_handle.custom_api_exception_handler",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=2),
    # "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    # "REFRESH_TOKEN_LIFETIME": timedelta(minutes=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
# CORS_ALLOW_ALL_ORIGINS = True
# LAN browser origins: LAN_HOST (default 192.168.1.4); subnet in network_defaults.LAN_SUBNET_CIDR (not used as Origin).
_CORS_BASE = [
    "https://ppaa.or.tz",
    "http://ppaa.or.tz",
    "http://localhost:4001",
    "http://127.0.0.1:4001",
    # Vite dev server (ppaa-internal-portal-frontend/vite.config.js port 4002)
    "http://localhost:4002",
    "http://127.0.0.1:4002",
    "http://frontend.approval.ppaa",
    "http://minio.ppaa",
    "http://localhost:8092",
    "http://127.0.0.1:8092",
    # Docker nginx frontend (ppaa-internal-portal-frontend/docker-compose.yml → 3000:80)
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOWED_ORIGINS = merge_unique_origins(_CORS_BASE, lan_browser_origins())

# Make sure these match your CORS settings
CSRF_TRUSTED_ORIGINS = merge_unique_origins(_CORS_BASE, lan_browser_origins())





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'ppaa_portal',
    'ppaa_auth',
    'microservices.ppaa_performance',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_yasg',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'microservices.maoni',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ppaa_portal.audit_middleware.ApiActivityAuditMiddleware',
]


REST_FRAMEWORK.update({
    'DEFAULT_THROTTLE_RATES': {
        'user': '5000/day',      # Allow authenticated users 500 requests per day
        'anon': '10/minute',    # Allow anonymous users 20 requests per minute
        'burst': '5/second',   # Allow short bursts of 5 requests per second
        'sustained': '50/hour', # Limit long-term users to 50 requests per hour
    },
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
})


ROOT_URLCONF = 'ppaa_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ppaa_portal.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'ppaa_auth.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

AUTH_USER_MODEL = 'ppaa_auth.User'
DATABASES = build_databases()


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ---------- EMAIL (read from env) ----------
# Empty string in .env must not override defaults (get() returns "" otherwise).
EMAIL_BACKEND = (os.environ.get("EMAIL_BACKEND") or "django.core.mail.backends.smtp.EmailBackend").strip()
EMAIL_HOST = (os.environ.get("EMAIL_HOST") or "smtp.gmail.com").strip()
EMAIL_PORT = int((os.environ.get("EMAIL_PORT") or "587").strip() or "587")
EMAIL_HOST_USER = (os.environ.get("EMAIL_HOST_USER") or "").strip()
EMAIL_HOST_PASSWORD = (os.environ.get("EMAIL_HOST_PASSWORD") or "").strip()
# Accept "True"/"False" or 1/0
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() in ("true", "1", "yes")
# Docker Compose `environment` can set TLS while `env_file` still sets SSL — Django forbids both.
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    if EMAIL_PORT == 465:
        EMAIL_USE_TLS = False
    else:
        EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = (os.environ.get("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER or "webmaster@localhost").strip()

# Absolute portal URL for links in emails (e.g. Maoni new reply). Override with FRONTEND_URL in production.
FRONTEND_URL = (os.environ.get("FRONTEND_URL") or f"http://{LAN_HOST}:3000").strip()

# ---------- CELERY / REDIS ----------
# Default to localhost so manage.py runserver works without Docker hostname "redis".
_redis_default = "redis://127.0.0.1:6379/0"
REDIS_URL = (os.environ.get("REDIS_URL") or _redis_default).strip() or _redis_default
CELERY_BROKER_URL = (os.environ.get("CELERY_BROKER_URL") or REDIS_URL).strip() or REDIS_URL
CELERY_RESULT_BACKEND = (os.environ.get("CELERY_RESULT_BACKEND") or REDIS_URL).strip() or REDIS_URL
# Run tasks in-process (no broker/worker). Set via env for local dev without Redis.
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "").lower() in ("true", "1", "yes")

# Celery Beat: RMS deadline reminder emails (disable with RMS_REMINDERS_BEAT=0).
CELERY_BEAT_SCHEDULE = {}
if os.environ.get("RMS_REMINDERS_BEAT", "1").lower() not in ("0", "false", "no", "off"):
    CELERY_BEAT_SCHEDULE["rms-report-reminders-daily"] = {
        "task": "ppaa_portal.tasks.rms_send_report_reminders",
        "schedule": crontab(hour=6, minute=0),
    }

# Celery Beat: Maoni auto-escalation sweep (hourly).
if os.environ.get("MAONI_AUTO_ESCALATION_BEAT", "1").lower() not in ("0", "false", "no", "off"):
    CELERY_BEAT_SCHEDULE["maoni-auto-escalation-hourly"] = {
        "task": "ppaa_portal.tasks.maoni_auto_escalate_overdue_suggestions",
        "schedule": crontab(minute=0),
    }


# ---------- MICROSERVICES URLS ----------
AUTH_SERVICE_URL = os.getenv("AUTH_SERVICE_URL", "http://localhost:8000")

