# Generated by Django 5.1.5 on 2026-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('NEW', 'New'), ('RETIRED', 'Retired'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
