# Generated by Django 5.1.5 on 2026-01-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0002_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionallevel',
            name='code',
            field=models.CharField(help_text='Position/Designation code (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='positionallevel',
            name='name',
            field=models.CharField(help_text='Position/Designation name (e.g., Executive Secretary, HEAD OF ICT)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term'), ('TEMPORALLY', 'Temporally')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('NEW', 'New')], default='ACTIVE', max_length=20),
        ),
    ]
