# Generated by Cursor on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppaa_auth", "0002_alter_user_managers_alter_country_iso_code_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE auth_user
              ADD COLUMN IF NOT EXISTS created_by bigint NULL,
              ADD COLUMN IF NOT EXISTS updated_by bigint NULL,
              ADD COLUMN IF NOT EXISTS deleted_by bigint NULL;
            """,
            reverse_sql="""
            ALTER TABLE auth_user
              DROP COLUMN IF EXISTS created_by,
              DROP COLUMN IF EXISTS updated_by,
              DROP COLUMN IF EXISTS deleted_by;
            """,
        )
    ]

