# Generated by Cursor on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppaa_auth", "0003_add_missing_auth_user_audit_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
    ]

