# Generated by Django 5.1.5 on 2026-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0003_alter_positionallevel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('LONG_TERM', 'Long Term'), ('SUPER_USER', 'Super User'), ('TEMPORALLY', 'Temporally')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
