# Generated by Django 5.1.5 on 2026-04-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0003_repair_missing_ppaa_auth_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='directory',
        ),
    ]
