# Generated by Django 5.1.5 on 2026-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppaa_auth', '0007_alter_user_account_type_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('LONG_TERM', 'Long Term'), ('TEMPORALLY', 'Temporally')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
