from django.urls import path

from .spism_endpoints import (
    SpismActivityApprovalView,
    SpismActivityDetailView,
    SpismActivityDocumentDetailView,
    SpismActivityDocumentDownloadView,
    SpismActivityDocumentListCreateView,
    SpismActivityImplementationApprovalView,
    SpismActivityListCreateView,
    SpismActivitySubmitImplementationView,
    SpismAuditLogDetailView,
    SpismAuditLogListCreateView,
    SpismImplementationActivitiesView,
    SpismImplementationTargetsView,
    SpismKpiActualDetailView,
    SpismKpiActualListCreateView,
    SpismObjectiveApprovalView,
    SpismObjectiveDetailView,
    SpismObjectiveListCreateView,
    SpismObjectiveSubmitPackageView,
    SpismPendingApprovalsView,
    SpismPerformanceOfficersView,
    SpismQuarterlyDataDetailView,
    SpismQuarterlyDataListCreateView,
    SpismTargetApprovalView,
    SpismTargetAssignOfficerView,
    SpismTargetDetailView,
    SpismTargetListCreateView,
)
from .views import (
    DashboardSummaryView,
    FinancialYearDetailView,
    FinancialYearListCreateView,
    PerformanceAnalyticsView,
    PerformanceReportsView,
    SpismConfigView,
)

urlpatterns = [
    path("financial-years", FinancialYearListCreateView.as_view()),
    path("financial-years/", FinancialYearListCreateView.as_view()),
    path("financial-years/<uuid:uid>", FinancialYearDetailView.as_view()),
    path("financial-years/<uuid:uid>/", FinancialYearDetailView.as_view()),
    path("analytics", PerformanceAnalyticsView.as_view()),
    path("analytics/", PerformanceAnalyticsView.as_view()),
    path("reports", PerformanceReportsView.as_view()),
    path("reports/", PerformanceReportsView.as_view()),
    path("summary", DashboardSummaryView.as_view()),
    path("summary/", DashboardSummaryView.as_view()),
    path("config", SpismConfigView.as_view()),
    path("config/", SpismConfigView.as_view()),
    # SPISM planning & implementation
    path("objectives", SpismObjectiveListCreateView.as_view()),
    path("objectives/", SpismObjectiveListCreateView.as_view()),
    path("objectives/<uuid:uid>", SpismObjectiveDetailView.as_view()),
    path("objectives/<uuid:uid>/", SpismObjectiveDetailView.as_view()),
    path(
        "objectives/<uuid:uid>/submit-package",
        SpismObjectiveSubmitPackageView.as_view(),
    ),
    path(
        "objectives/<uuid:uid>/submit-package/",
        SpismObjectiveSubmitPackageView.as_view(),
    ),
    path("objectives/<uuid:uid>/approval", SpismObjectiveApprovalView.as_view()),
    path("objectives/<uuid:uid>/approval/", SpismObjectiveApprovalView.as_view()),
    path("targets", SpismTargetListCreateView.as_view()),
    path("targets/", SpismTargetListCreateView.as_view()),
    path("targets/<uuid:uid>", SpismTargetDetailView.as_view()),
    path("targets/<uuid:uid>/", SpismTargetDetailView.as_view()),
    path(
        "targets/<uuid:uid>/assign-officer",
        SpismTargetAssignOfficerView.as_view(),
    ),
    path(
        "targets/<uuid:uid>/assign-officer/",
        SpismTargetAssignOfficerView.as_view(),
    ),
    path("targets/<uuid:uid>/approval", SpismTargetApprovalView.as_view()),
    path("targets/<uuid:uid>/approval/", SpismTargetApprovalView.as_view()),
    path("activities", SpismActivityListCreateView.as_view()),
    path("activities/", SpismActivityListCreateView.as_view()),
    path("activities/<uuid:uid>", SpismActivityDetailView.as_view()),
    path("activities/<uuid:uid>/", SpismActivityDetailView.as_view()),
    path("activities/<uuid:uid>/approval", SpismActivityApprovalView.as_view()),
    path("activities/<uuid:uid>/approval/", SpismActivityApprovalView.as_view()),
    path(
        "activities/<uuid:uid>/implementation-approval",
        SpismActivityImplementationApprovalView.as_view(),
    ),
    path(
        "activities/<uuid:uid>/implementation-approval/",
        SpismActivityImplementationApprovalView.as_view(),
    ),
    path(
        "activities/<uuid:uid>/submit-implementation",
        SpismActivitySubmitImplementationView.as_view(),
    ),
    path(
        "activities/<uuid:uid>/submit-implementation/",
        SpismActivitySubmitImplementationView.as_view(),
    ),
    path("quarterly-data", SpismQuarterlyDataListCreateView.as_view()),
    path("quarterly-data/", SpismQuarterlyDataListCreateView.as_view()),
    path("quarterly-data/<uuid:uid>", SpismQuarterlyDataDetailView.as_view()),
    path("quarterly-data/<uuid:uid>/", SpismQuarterlyDataDetailView.as_view()),
    path("kpi-actuals", SpismKpiActualListCreateView.as_view()),
    path("kpi-actuals/", SpismKpiActualListCreateView.as_view()),
    path("kpi-actuals/<uuid:uid>", SpismKpiActualDetailView.as_view()),
    path("kpi-actuals/<uuid:uid>/", SpismKpiActualDetailView.as_view()),
    path("activity-documents", SpismActivityDocumentListCreateView.as_view()),
    path("activity-documents/", SpismActivityDocumentListCreateView.as_view()),
    path(
        "activity-documents/<uuid:uid>",
        SpismActivityDocumentDetailView.as_view(),
    ),
    path(
        "activity-documents/<uuid:uid>/",
        SpismActivityDocumentDetailView.as_view(),
    ),
    path(
        "activity-documents/<uuid:uid>/download",
        SpismActivityDocumentDownloadView.as_view(),
    ),
    path(
        "activity-documents/<uuid:uid>/download/",
        SpismActivityDocumentDownloadView.as_view(),
    ),
    path("audit-logs", SpismAuditLogListCreateView.as_view()),
    path("audit-logs/", SpismAuditLogListCreateView.as_view()),
    path("audit-logs/<uuid:uid>", SpismAuditLogDetailView.as_view()),
    path("audit-logs/<uuid:uid>/", SpismAuditLogDetailView.as_view()),
    path("performance-officers", SpismPerformanceOfficersView.as_view()),
    path("performance-officers/", SpismPerformanceOfficersView.as_view()),
    path("pending-approvals", SpismPendingApprovalsView.as_view()),
    path("pending-approvals/", SpismPendingApprovalsView.as_view()),
    path("implementation-activities", SpismImplementationActivitiesView.as_view()),
    path("implementation-activities/", SpismImplementationActivitiesView.as_view()),
    path("implementation-targets", SpismImplementationTargetsView.as_view()),
    path("implementation-targets/", SpismImplementationTargetsView.as_view()),
]
